### ISSUE TITLE
ASMR.yaml file not found

### ISSUE THREAD

**Issue by xingliangwang1117** [BoseungJeong/ASMR#2]
![image](https://user-images.githubusercontent.com/129079573/228440751-08cc7e93-e67f-4f1b-afab-968bdd3c47b3.png)
could you tell me where is ASMR.yaml

**Comment by wong00** [comment]
> 
There is no need to use ASMR.yaml  and also  the author doesn't provide that.

**Comment by xingliangwang1117** [comment]
Do you mean that in the author's Installation section just go into ASMR-ICCV-2021-main, no need to execute conda env create -f ASMR.yaml and conda activate ASMR?

**Comment by wong00** [comment]
是 你自己的虚拟环境只要有代码里的那些库就可以了  哪个少了直接pip安装就可以

**Comment by xingliangwang1117** [comment]
好的，谢谢你。我还想请问下，你有训练好了的模型吗，我感觉我的笔记本应该训练不下来。

**Comment by xingliangwang1117** [comment]
> 是 你自己的虚拟环境只要有代码里的那些库就可以了 哪个少了直接pip安装就可以

请问你当时训练，C盘预留了多少空间啊，8个G够不够啊

**Comment by wong00** [comment]
> > 是 你自己的虚拟环境只要有代码里的那些库就可以了 哪个少了直接pip安装就可以
> 
> 请问你当时训练，C盘预留了多少空间啊，8个G够不够啊

我在服务器上训练的 大概10G显存  你要在cpu上训练？
